function buildSummaryBlocks(summary) {
    return [
        {
            type: "header",
            text: {
                type: "plain_text",
                text: "🛡 API Guardian AI",
            },
        },

        {
            type: "section",
            fields: [
                {
                    type: "mrkdwn",
                    text: `*🟢 System Health*\n${summary.health}`,
                },
                {
                    type: "mrkdwn",
                    text: `*📊 Requests*\n${summary.requests}`,
                },
                {
                    type: "mrkdwn",
                    text: `*⚡ Avg Latency*\n${summary.latency} ms`,
                },
                {
                    type: "mrkdwn",
                    text: `*💾 Memory*\n${summary.memory}%`,
                },
                {
                    type: "mrkdwn",
                    text: `*🖥 CPU*\n${summary.cpu}%`,
                },
                {
                    type: "mrkdwn",
                    text: `*🚨 Active Incidents*\n${summary.incidents}`,
                },
            ],
        },

        {
            type: "divider",
        },

        {
            type: "section",
            text: {
                type: "mrkdwn",
                text:
                    "*💡 AI Recommendation*\n\n" +
                    summary.recommendation,
            },
        },

        {
            type: "context",
            elements: [
                {
                    type: "mrkdwn",
                    text:
                        "Generated by API Guardian AI • Powered by Groq",
                },
            ],
        },
    ];
}

module.exports = {
    buildSummaryBlocks,
};